name: vox_guard
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.10.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0         # المكتبة البديلة لخرائط جوجل
  latlong2: ^0.9.0            # للتعامل مع الإحداثيات (Latitude/Longitude)
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  
  intl_phone_field: ^3.2.0
  permission_handler: ^11.3.1
  http: ^1.6.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  geocoding: ^4.0.0
  image_picker: ^1.2.1
  
  # المكتبات التي تم دمجها بنجاح:
  audioplayers: ^5.2.1
  dio: ^5.9.2
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints.
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is included.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/audio/